### ISSUE TITLE
Warning from 'Provider' is popping out with every component update.

### ISSUE THREAD

**Issue by juanenrisley** [RobinBuschmann/react.di#14]
The warning 'Container can only be set once to <Provider> and therefore not be overridden.' is just being logged with every action.

**Comment by RobinBuschmann** [comment]
Thanks for reporting.

**Comment by juanenrisley** [comment]
Thanks to you for this great library! I have been having trouble with inversify and you solved that.

**Comment by RobinBuschmann** [comment]
Closing this, since it is fixed with the latest release
