### ISSUE TITLE
How do I create or manually inject dependencies into a regular (non-React) object?

### ISSUE THREAD

**Issue by ashleydavis** [RobinBuschmann/react.di#15]
I've been using your DI library in my React and it's been working great! Thanks so much for your work.

Recently though I started converting my app to use the command pattern and this led me to want to create and resolve dependencies for command objects.

For example a command to open a file:

```
export class OpenFileCommand implements ICommand {
    @Inject("ILog")
    log?: ILog;
    
     async invoke(): Promise<void> {
          // ... do the action of the command ...
     }
}
```

Normally I'd instantiate an object like so:

`const command = new OpenFileCommand();
`

The question is how do I make this object be dependency injected? I want to resolve all of it's dependencies when it's constructed.

Do you provide a way to run the dependency injector on an existing object?

Or do you provide a factory that can instantiate and inject the class?

Thanks so much
Ash

**Comment by RobinBuschmann** [comment]
Hey @ashleydavis, see https://github.com/RobinBuschmann/react.di#inject-into-services for preparing your class to be injectable (`@Injectable` annotation) and don't forget to add the class reference to the module, where you want to use this class: https://github.com/RobinBuschmann/react.di#3-setup-module

Hope this helps!

**Comment by ashleydavis** [comment]
Thanks for your quick reply!

I have read those docs and I know how to setup a service to be injected into a React component. That works great I'm using it across my UI hierarchy already.

What I need to do now is inject services into a regular TypeScript class. Can that be done? I haven't seen anything in your docs about it.

**Comment by ashleydavis** [comment]
It would also answer my question if you could tell me how to manually instantiate a service using react.di.

**Comment by RobinBuschmann** [comment]
@ashleydavis in which context do you need to create an instance of a class? react.di is designed to start from a react component. So the dependency container is created when annotating mostly a react component class with `@Module`. Can you provide a more complex example of what you're trying to achieve?

**Comment by ashleydavis** [comment]
I provided the example already. I want to inject services into my command object from the earlier example.

Or the alternate question is can you just show me a line of code that illustrates how I might instantiate a service and have its dependencies resolved.

I'm guessing react.di just isn't general purpose like that. If that's the case it means I need an alternative DI library to inject my non-React objects. It's that correct?

I was hoping I could have it all with your library.

**Comment by RobinBuschmann** [comment]
At some point you need to initialize your application. This is also the starting point of DI, so the point where the main DI container is created. In react.di this is a react component. So the following are your options to create an instance of a class in the context of the DI container:

```ts
// main.ts
import {Module} from 'react.di';

@Module({
  providers: [
    {provide: 'ILog', useClass: Logger},
    OpenFileCommand,
    SomeService,
  ]
})
class App extends Component {

  @Inject service: SomeService;
  @Inject openFileCommand: OpenFileCommand; // option A

  async componentDidMount() {
    this.service.doSomething();
    await this.openFileCommand.invoke();
  }
  render() {
    return (
          <div></div>
    );
  }
}
```

```ts
// some-service.ts
import {Injectable} from 'react.di';

@Injectable
export class SomeService {
  constructor(private openFileCommand: OpenFileCommand) { // option B
  }
}
```

```ts
// open-file-command.ts
import {Injectable} from 'react.di';

@Injectable
export class OpenFileCommand {
  // ...
}
```

**Comment by ashleydavis** [comment]
Ok thanks for that , that's a potentially useable setup for me.

But just to clarify, I can't do this and expect it to be injected:

`const command  = new OpenFileCommand();`

**Comment by RobinBuschmann** [comment]
No, you would need to access the container, which is internally created by react.di for you, and then do something like:
```ts
const command = container.get(OpenFileCommand);
```
See example when doing it with pure inversify: 
https://github.com/inversify/InversifyJS#step-4-resolve-dependencies

.. or with injection-js:  
https://github.com/mgechev/injection-js#typescript

**Comment by ashleydavis** [comment]
Thanks so much for your help. I'll let you know how it ends up.

**Comment by ashleydavis** [comment]
Another quick question I have relating to this.

Is it possible to extract the root container from the react.di library?

Or is it possible for me to control instantiation of the root container and inject it into the react.di library?

**Comment by RobinBuschmann** [comment]
You could use the `Provider` component instead of the `Module` annotation: https://github.com/RobinBuschmann/react.di#provider-react-component 
With this approach you are able set up the inversify container on your own.

**Comment by ashleydavis** [comment]
Ok. Thanks for putting me on the right track!
